### ISSUE TITLE
On launch through debugging, this PR introduces a warning right away regarding with pydantic.

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-core#42]
@Orbitix on launch through debugging, this PR introduces a warning right away regarding with pydantic.

```
/home/wlanpi/dev/wlanpi-core/venv/lib/python3.9/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
```

Our pydantic version pin is 2.3.0. Please use a v2 compatible approach here.

_Originally posted by @joshschmelzle in https://github.com/WLAN-Pi/wlanpi-core/pull/27#discussion_r1785623699_

**Comment by Orbitix** [comment]
Fixed with PR #44
