### ISSUE TITLE
Development Environment Codification

### ISSUE THREAD

**Issue by crvallance** [WLAN-Pi/wlanpi-core#57]
Without a functional WLAN-Pi it's currently very hard to do development work on this repo unless you install several things in a Linux environment that may conflict with your working system. Virtual machines are a suitable workaround but without specific build instructions, developers could end up with very different environments which can lead to hard to track errors, bugs, and a tough on-boarding experience for new developers. I think this could be solved in a couple ways:

- Create automation for a dev VM
- Create a standalone container
- Create a .devcontainer spec that works in conjunction with a container

I've got a drafted .devcontainer that I will PR for review but wanted to start a discussion.

**Comment by joshschmelzle** [comment]
Closed by #58
